[tool.poetry]
name = "jaddek_tillo_http_client"
version = "0.0.3"
description = "Tillo HTTP Client"
authors = ["tonynazarov <tonynazarov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.0"
httpx = { extras = ["http2"], version = "^0.28.0" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.urls]
Homepage = "https://github.com/jaddek/tillo-http-client"